gnome-keyring: Autospec creation for update from version 46.1 to version 46.2
Aefgh Threenine (1):
      Update Thai translation

Alexandre Franke (1):
      Update French translation

Andre Klapper (3):
      HACKING: Correct 404 URI to Architecture on wiki
      HACKING: Replace defunct Bugzilla and mailing list with GitLab and Discourse
      docs: Replace defunct Bugzilla with GitLab URI

Dan Nicholson (1):
      build: Fix distcheck with systemd units

Guntupalli Karunakar (1):
      Update Hindi translation

Jeremy Bícha (1):
      rpc-layer: Fix undefined reference to g_strlcpy

Jordan Petridis (1):
      Release 46.2

Niels De Graef (2):
      autogoo: replace AC_HELP_STRING with AS_HELP_STRING
      Don't use `bool` as variable name

Rachida SACI (2):
      Add Kabyle translation
      Update Kabyle translation

Ryan Hendrickson (1):
      Default "automatically unlock" checkbox to false

Changes in version 46.2 are:
 * Don't use `bool` as variable name
 * autogoo: replace AC_HELP_STRING with AS_HELP_STRING
 * Default "automatically unlock" checkbox to false
 * build: Fix distcheck with systemd unit
 * rpc-layer: Fix undefined reference to g_strlcpy
 * Updated translations